jmose_command_scheduler_list_overview:
    pattern:  /command-scheduler/
    defaults:
      _controller: JMoseCommandSchedulerBundle:Base:index

# lists
jmose_command_scheduler_list_details:
    pattern:  /command-scheduler/list/{_type}
    defaults:
      _controller: JMoseCommandSchedulerBundle:List:index
    requirements:
      _type: "commands|rights|executions"

jmose_command_scheduler_action:
    resource: @JMoseCommandSchedulerBundle/Resources/config/routing_action.yml
    prefix:   /command-scheduler/action

jmose_command_scheduler_detail:
    resource: @JMoseCommandSchedulerBundle/Resources/config/routing_detail.yml
    prefix:   /command-scheduler/detail

# misc
jmose_command_scheduler_monitor:
    pattern:  /command-scheduler/monitor
    defaults: { _controller: JMoseCommandSchedulerBundle:Monitor:monitor }
