# list actions
jmose_command_scheduler_action_toggle:
    pattern:  /command-scheduler/action/toggle/{id}
    defaults: { _controller: JMoseCommandSchedulerBundle:List:toggle }

jmose_command_scheduler_action_remove:
    pattern:  /command-scheduler/action/remove/{id}
    defaults: { _controller: JMoseCommandSchedulerBundle:List:remove }

jmose_command_scheduler_action_execute:
    pattern:  /command-scheduler/action/execute/{id}
    defaults: { _controller: JMoseCommandSchedulerBundle:List:execute }

jmose_command_scheduler_action_unlock:
    pattern:  /command-scheduler/action/unlock/{id}
    defaults: { _controller: JMoseCommandSchedulerBundle:List:unlock }
