# detail actions
jmose_command_scheduler_detail_command_index:
    pattern:  /view/
    defaults: { _controller: JMoseCommandSchedulerBundle:Detail:indexCommand }

jmose_command_scheduler_detail_command_edit:
    pattern:  /edit/{scheduledCommandId}
    defaults: { _controller: JMoseCommandSchedulerBundle:Detail:initEditScheduledCommand }

jmose_command_scheduler_detail_command_new:
    pattern:  /new
    defaults: { _controller: JMoseCommandSchedulerBundle:Detail:initNewScheduledCommand }

jmose_command_scheduler_detail_command_save:
    pattern:  /save
    defaults: { _controller: JMoseCommandSchedulerBundle:Detail:saveCommand }

jmose_command_scheduler_detail_command_executions:
    pattern:  /executions/{scheduledCommandId}
    defaults: { _controller: JMoseCommandSchedulerBundle:Detail:showExecutions }
