# detail actions
#jmose_command_scheduler_detail_command_index:
#    pattern:  /commands/view/
#    defaults: { _controller: JMoseCommandSchedulerBundle:Command:indexCommand }

jmose_command_scheduler_detail_command_edit:
    pattern:  /commands/edit/{scheduledCommandId}
    defaults: { _controller: JMoseCommandSchedulerBundle:Command:initEditScheduledCommand }

jmose_command_scheduler_detail_command_new:
    pattern:  /commands/new
    defaults: { _controller: JMoseCommandSchedulerBundle:Command:initNewScheduledCommand }

jmose_command_scheduler_detail_command_save:
    pattern:  /commands/save
    defaults: { _controller: JMoseCommandSchedulerBundle:Command:saveCommand }

jmose_command_scheduler_detail_command_executions:
    pattern:  /commands/executions/{commandId}
    defaults: { _controller: JMoseCommandSchedulerBundle:Execution:showCommandExecutions }

# user/host requirements
#jmose_command_scheduler_detail_rights_index:
#    pattern:  /rights/view/
#    defaults: { _controller: JMoseCommandSchedulerBundle:Rights:indexCommand }

jmose_command_scheduler_detail_rights_edit:
    pattern:  /rights/edit/{scheduledCommandId}
    defaults: { _controller: JMoseCommandSchedulerBundle:Command:initEditScheduledCommand }

jmose_command_scheduler_detail_rights_new:
    pattern:  /rights/new
    defaults: { _controller: JMoseCommandSchedulerBundle:Right:initNewUserHost }

jmose_command_scheduler_detail_rights_save:
    pattern:  /rights/save
    defaults: { _controller: JMoseCommandSchedulerBundle:Command:saveCommand }

