# lists
jmose_command_scheduler_list:
    pattern:  /command-scheduler/list
    defaults: { _controller: JMoseCommandSchedulerBundle:List:index }

jmose_command_scheduler_list_rights:
    pattern:  /command-scheduler/listRights
    defaults: { _controller: JMoseCommandSchedulerBundle:List:indexRights }

jmose_command_scheduler_action:
    resource:  @JMoseCommandSchedulerBundle/Resources/config/routing_action.yml
    prefix:   /command-scheduler/action

jmose_command_scheduler_detail:
    resource: @JMoseCommandSchedulerBundle/Resources/config/routing_detail.yml
    prefix:   /command-scheduler/detail

# misc
jmose_command_scheduler_monitor:
    pattern:  /command-scheduler/monitor
    defaults: { _controller: JMoseCommandSchedulerBundle:List:monitor }
