# list actions
jmose_command_scheduler_action_command_toggle:
    pattern:  /toggle/command/{id}
    defaults: { _controller: JMoseCommandSchedulerBundle:List:toggleCommand }

jmose_command_scheduler_action_command_toggle_logging:
    pattern:  /toggleLogging/command/{id}
    defaults: { _controller: JMoseCommandSchedulerBundle:List:toggleLogging }

jmose_command_scheduler_action_command_remove:
    pattern:  /remove/command/{id}
    defaults: { _controller: JMoseCommandSchedulerBundle:List:removeCommand }

jmose_command_scheduler_action_command_execute:
    pattern:  /execute/command/{id}
    defaults: { _controller: JMoseCommandSchedulerBundle:List:executeCommand }

jmose_command_scheduler_action_command_unlock:
    pattern:  /unlock/command/{id}
    defaults: { _controller: JMoseCommandSchedulerBundle:List:unlockCommand }
