services:
    jmose_command_scheduler.command_choice_list:
        class: JMose\CommandSchedulerBundle\Form\CommandChoiceList
        arguments:
            - @kernel
            - %jmose_command_scheduler.excluded_command_namespaces%
