services:
    JMose\CommandSchedulerBundle\Service\CommandParser:
        arguments:
            - "@kernel"
            - "%jmose_command_scheduler.excluded_command_namespaces%"

    JMose\CommandSchedulerBundle\Form\Type\CommandChoiceType:
        autowire: true
        tags:
            - { name: form.type, alias: command_choice }

    JMose\CommandSchedulerBundle\Service\SchedulerService:
        shared: false
        public: true
        arguments:
            - "@doctrine"

    JMose\CommandSchedulerBundle\Command\ExecuteCommand:
        tags: [console.command]

    JMose\CommandSchedulerBundle\Command\MonitorCommand:
        tags: [console.command]

    JMose\CommandSchedulerBundle\Command\UnlockCommand:
        tags: [console.command]
